CREATE TABLE USER(
    USER_UUID VARCHAR(36) PRIMARY KEY,
    CREATED DATE,
    MODIFIED DATE,
    LAST_LOGIN DATE,
    TOKEN VARCHAR(255),  
    ISACTIVE BOOLEAN,
    USER_NAME VARCHAR(60),
    EMAIL VARCHAR(60),
    USER_PASSWORD VARCHAR(1024)    
);

CREATE TABLE PHONE(
    PHONE_UUID VARCHAR(36) PRIMARY KEY,
    USER_UUID VARCHAR(36),
    PHONE_NUMBER VARCHAR(40),
    CITY_CODE VARCHAR(40),
    COUNTRY_CODE VARCHAR(40)
);

ALTER TABLE PHONE ADD FOREIGN KEY(USER_UUID) REFERENCES USER(USER_UUID);